# Generated by Django 5.0.3 on 2024-04-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_delete_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'permissions': [('can_deliver_pizzas', 'Can deliver pizzas')]},
        ),
    ]
